[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-initialize",
  "allow-register-listener",
  "allow-remove-listener",
  "allow-set-source",
  "allow-set-queue",
  "allow-next",
  "allow-previous",
  "allow-skip-to",
  "allow-add-to-queue",
  "allow-update-queue",
  "allow-remove-from-queue",
  "allow-move-in-queue",
  "allow-set-volume",
  "allow-get-output-devices",
  "allow-set-output-device",
  "allow-get-queue",
  "allow-restore-last-queue",
  "allow-play",
  "allow-pause",
  "allow-seek-to",
  "allow-set-rate",
  "allow-set-skip-interval",
  "allow-set-shuffle",
  "allow-set-repeat-mode",
  "allow-set-library",
  "allow-set-options",
  "allow-set-controls",
  "allow-set-control-active",
  "allow-get-control-presses",
  "allow-acknowledge-control-presses",
  "allow-get-playback-events",
  "allow-acknowledge-playback-events",
  "allow-set-tracked-lists",
  "allow-get-tracked-list",
  "allow-set-tracked-list",
  "allow-get-tracked-list-changes",
  "allow-acknowledge-tracked-list-changes",
  "allow-set-sleep-timer",
  "allow-cancel-sleep-timer",
  "allow-get-item-progress",
  "allow-set-item-progress",
  "allow-get-state",
  "allow-get-progress-checkpoint",
  "allow-clear-progress-checkpoint",
  "allow-dispose",
]
